### ISSUE TITLE
프론트엔드 서버에 대해서 조사

### ISSUE THREAD

**Issue by Sith-call** [Techeer-FM-Studio/frontend#6]
* next.js에서 제공하는 custom server 방식과 nginx에서 바로 ssr하는 방식의 차이점을 조사해오기
* 최종적으로 어떤 방식을 사용할 지에 대한 근거가 있어야 함

**Comment by JunJongHun** [comment]
https://unruly-stallion-b93.notion.site/next-js-c2b0ebf9422b47cb9bb14179faf3beda
